#!/bin/bash

## Author: Taylor Jenkins
## Date: March 25, 2017
## License: MIT
## Description: A script to list all active VNC processes, 
##              formatted to include relevant information.

## Note:
## To create Linux command from this script:
## save it as the name of the command, for example: lsvnc
## chmod +x lsvnc
## cp lsvnc /usr/bin/

## Improves upon this script, which also lists active VNC Server processes
#ps -ef | grep vnc

## Generates a formatted list of active VNC processes 
## conditional statements handle the error for when there are no VNC processes
if pgrep vnc;
then
  echo Active VNC processes:
  ps -o user,pid,ppid,session,stat,pcpu,pmem,command -p $(pgrep vnc);
else echo No active VNC processes;
fi

## Brief formatted list of active VNC processes 
#if pgrep vnc;
#then 
#  echo Active VNC processes:
#  ps -p $(pgrep vnc)
#else echo No active VNC processes;
#fi